// The MIT License (MIT)
// Copyright © 2014-2018 Miguel Peláez <kernelfreeze@outlook.com>
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation
// files (the “Software”), to deal in the Software without restriction, including without limitation the rights to use, copy,
// modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software
// is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
// LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR
// IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

/// Regions in a Minecraft world with varying geographical features, flora,
/// heights, temperatures, humidity ratings, and sky and foliage colors.
pub enum Biome {
    Ocean,
    Plains,
    Desert,
    Mountains,
    Forest,
    Taiga,
    Swamp,
    River,
    Nether,
    TheEnd,
    FrozenOcean,
    FrozenRiver,
    SnowyTundra,
    SnowyMountains,
    MushroomFields,
    MushroomFieldShore,
    Beach,
    DesertHills,
    WoodedHills,
    TaigaHills,
    MountainEdge,
    Jungle,
    JungleHills,
    JungleEdge,
    DeepOcean,
    StoneShore,
    SnowyBeach,
    BirchForest,
    BirchForestHills,
    DarkForest,
    SnowyTaiga,
    SnowyTaigaHills,
    GiantTreeTaiga,
    GiantTreeTaigaHills,
    WoodedMountains,
    Savanna,
    SavannaPlateau,
    Badlands,
    WoodedBadlandsPlateau,
    BadlandsPlateau,
    SmallEndIslands,
    EndMidlands,
    EndHighlands,
    EndBarrens,
    WarmOcean,
    LukewarmOcean,
    ColdOcean,
    DeepWarmOcean,
    DeepLukewarmOcean,
    DeepColdOcean,
    DeepFrozenOcean,
    TheVoid,
    SunflowerPlains,
    DesertLakes,
    GravellyMountains,
    FlowerForest,
    TaigaMountains,
    SwampHills,
    IceSpikes,
    ModifiedJungle,
    ModifiedJungleEdge,
    TallBirchForest,
    TallBirchHills,
    DarkForestHills,
    SnowyTaigaMountains,
    GiantSpruceTaiga,
    GiantSpruceTaigaHills,
    GravellyMountainsPlus,
    ShatteredSavanna,
    ShatteredSavannaPlateau,
    ErodedBadlands,
    ModifiedWoodedBadlandsPlatea,
    ModifiedBadlandsPlateau,
    Custom(u8),
}

impl Biome {
    /// Each type of biome has its own ***biome id***
    pub fn id(&self) -> u8 {
        use core::biome::Biome::*;
        
        match self {
            Ocean => 0,
            Plains => 1,
            Desert => 2,
            Mountains => 3,
            Forest => 4,
            Taiga => 5,
            Swamp => 6,
            River => 7,
            Nether => 8,
            TheEnd => 9,
            FrozenOcean => 10,
            FrozenRiver => 11,
            SnowyTundra => 12,
            SnowyMountains => 13,
            MushroomFields => 14,
            MushroomFieldShore => 15,
            Beach => 16,
            DesertHills => 17,
            WoodedHills => 18,
            TaigaHills => 19,
            MountainEdge => 20,
            Jungle => 21,
            JungleHills => 22,
            JungleEdge => 23,
            DeepOcean => 24,
            StoneShore => 25,
            SnowyBeach => 26,
            BirchForest => 27,
            BirchForestHills => 28,
            DarkForest => 29,
            SnowyTaiga => 30,
            SnowyTaigaHills => 31,
            GiantTreeTaiga => 32,
            GiantTreeTaigaHills => 33,
            WoodedMountains => 34,
            Savanna => 35,
            SavannaPlateau => 36,
            Badlands => 37,
            WoodedBadlandsPlateau => 38,
            BadlandsPlateau => 39,
            SmallEndIslands => 40,
            EndMidlands => 41,
            EndHighlands => 42,
            EndBarrens => 43,
            WarmOcean => 44,
            LukewarmOcean => 45,
            ColdOcean => 46,
            DeepWarmOcean => 47,
            DeepLukewarmOcean => 48,
            DeepColdOcean => 49,
            DeepFrozenOcean => 50,
            TheVoid => 127,
            SunflowerPlains => 129,
            DesertLakes => 130,
            GravellyMountains => 131,
            FlowerForest => 132,
            TaigaMountains => 133,
            SwampHills => 134,
            IceSpikes => 140,
            ModifiedJungle => 149,
            ModifiedJungleEdge => 151,
            TallBirchForest => 155,
            TallBirchHills => 156,
            DarkForestHills => 157,
            SnowyTaigaMountains => 158,
            GiantSpruceTaiga => 160,
            GiantSpruceTaigaHills => 161,
            GravellyMountainsPlus => 162,
            ShatteredSavanna => 163,
            ShatteredSavannaPlateau => 164,
            ErodedBadlands => 165,
            ModifiedWoodedBadlandsPlatea => 166,
            ModifiedBadlandsPlateau => 167,
            Custom(id) => id.clone(),
        }
    }
}
